### PR TITLE
Add linting to tests

### PR DESCRIPTION
**Pull request by SimenB**
Saw you recently did some fixing of it, thought to complete the process :smile: 

I disabled the `no-undefined` rule for the tests. I could switch usage from `undefined` to `null` instead perhaps?

Also, what about setting up travis or one of its brethren to automatically build PRs? I can see from the coverage badge that code climate is set up, but AFAIK they don't build PRs, do they?
Found [this](http://docs.codeclimate.com/article/213-github-pull-request-integration) which seems to indicate something, but I'm unsure if it runs `npm test` or what.

### CODE REVIEW

**Comment by rossPatton** [comment]
Why null over undefined? Checking for null is a pain, using undefined is much easier.

Code Climate afaik just does static analysis on the master branch. The PR integration looks cool, but I don't see it doing much.

Setting up travis would be neat, I only have experience with codeship but i'm sure they're all the same.

**Comment by SimenB** [comment]
Null was just a suggestion to _not_ disable the rule, I agree that `undefined` is more semantically correct :smile:

**Comment by SimenB** [comment]
For travis, just log in with you github-account and enable the repo

**Comment by SimenB** [comment]
@rossPatton I was just about to make a PR with a `.travis.yml`, then I saw you added it. Neat!

FWIW this is my:
```yml
language: node_js
node_js:
  - iojs
  - iojs-2
  - iojs-1
  - node # could be 0.12 as the next release of node will be 4.0 (merged with iojs)
  - '0.10'
addons:
  code_climate:
    repo_token: # enter token here
after_success: codeclimate-test-reporter < coverage/lcov.info
```

This runs the tests on every stable release since `0.10`. If you add your repo-token from codeclimate, it automatically reports coverage on builds. You also have to add `codeclimate-test-reporter` to `devDeps`

**Pull request merged**
