### PR TITLE
[WIP] Add column number to warning message details

### PR DESCRIPTION
**Pull request by wojciechczerniak**
:warning: WORK IN PROGRESS :warning:

Since I will have to touch every file in checks folder I'm starting this PR early to ask for opinion. I will continue to add columnNo for each check in following commits.

ESLint and sass-lint reporters have column number where the warning occurred. This will allow to highlight the right place in the code editor instead of the whole line.

stylint-columnno-1
stylint-columnno-2
stylint-columnno-3

Return -1 by default if whole line should be highlighted or check does not support column number (yet).

TODO:

- [x] blocks
- [x] brackets
- [x] colons
- [x] colors
- [x] commaSpace
- [x] commentSpace
- [x] cssLiteral
- [x] depthLimit
- [x] duplicates
- [x] efficient
- [x] extendPref
- [x] indentPref
- [x] leadingZero
- [x] mixed
- [x] namingConvention
- [x] none
- [x] noImportant
- [x] parenSpace
- [x] placeholders
- [ ] prefixVarsWithDollar
- [ ] quotePref
- [x] semicolons
- [x] sortOrder
- [x] stackedProperties
- [x] trailingWhitespace
- [x] universal
- [x] valid
- [x] zeroUnits
- [x] zIndexNormalize

### CODE REVIEW

**Comment by rossPatton** [comment]
i think this is a great idea, btw

**Comment by SimenB** [comment]
Oh, sweet!

Btw, how did you get the report into your IDE? I can see it's a JetBrains IDE, but I didn't know you could add custom linters to it.

**Comment by wojciechczerniak** [comment]
Cool, I'll work on the remaining checks.

You can add a linter by creating JetBrains plugin. I'll publish it soon.

**Comment by rossPatton** [comment]
closing as stylint now has this feature (for most checks anyway)

**Pull request closed without merging**
