### PR TITLE
Resolve colon always checks with certain CSS selectors and at-rules

### PR DESCRIPTION
**Pull request by anthonyjruffa**
Fixes the issues highlighted in #130 to account for multiple selectors such as the `+` and `~` selectors and resolve issues with at-rules.

### CODE REVIEW

**Comment by rossPatton** [comment]
Awesome, thanks! I'll review this tonight maybe

**Comment by anthonyjruffa** [comment]
Great!  I rebased off of develop since this is against that branch.

Let me know if you have any feedback.

**Comment by rossPatton** [comment]
:+1:

**Comment by anthonyjruffa** [comment]
Hey do you know when this will get implemented into production? Thanks!

**Comment by rossPatton** [comment]
It should be up now, in the latest version (1.0.11)

**Comment by anthonyjruffa** [comment]
So I ran 1.0.11 and it still throws errors in the instance of (comma-separated) multiple selectors on the same line.

I removed the last comma before the `$` in the `ignoreRe` regex and it fixed the problem on this line:

https://github.com/rossPatton/stylint/blob/master/src/checks/colons.js#L5

Do you want to go ahead with this fix?

**Comment by rossPatton** [comment]
Yeah, there was a regression, no biggie. Removing the $ will probably cause another case to fail, i'll just have to take another pass at it. I should have time tomorrow.

**Comment by anthonyjruffa** [comment]
Interesting, does the comma preceding the `$` also need to be there? If not, taking that out would do it.  If so, I will take another look at it soon.

**Pull request merged**
